import React from 'react'
import ReactDOM from 'react-dom/client'
import { HelmetProvider } from 'react-helmet-async'
// Local icon set, generated by scripts/generate-icon-css.mjs. Replaces the two
// third-party icon-font stylesheets that used to block first paint.
import './assets/icons.css'
import './index.css'
import App from './App.jsx'
import { LanguageProvider } from './i18n/LanguageContext.jsx'
import { registerServiceWorker } from './registerServiceWorker.js'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <HelmetProvider>
      <LanguageProvider>
        <App />
      </LanguageProvider>
    </HelmetProvider>
  </React.StrictMode>
)

registerServiceWorker()
